# Dependencies
markdown            : kramdown
redcarpet:
  extensions        : ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
highlighter         : rouge
gems                : ["jekyll-paginate"]

# Permalinks
permalink           : pretty

# Setup
title               : Toolbuddy Tech Notes
tagline             : 'Toolbuddy Tech Notes'
description         : 'Make the world a better place.'
baseurl             : https://toolbuddy.github.io/

author              : Toolbuddy
name                : 'Toolbuddy'
url                 : https://toolbuddy.github.io/

paginate            : 5

# Custom vars
version             : 0.1.0
github_username     : toolbuddy
